language: node_js
node_js:
- 8.11.2
deploy:
  api_key:
    secure: BGBlxp8Q6j4qlrGUYshn2WOz/XdgysJIjANXmB/aTf2a910vVnCCwOeVgwpqc4chWjsVGqzDbTSbL0QW6p3Rkb9NJ6CpfRntk+ePAUyBqsT1CxxU89iJ4QV1yCkkYMyJU6U9JF1xcodpjBQ3lOPZLHvERCXn2M+MoCixwX2w/eVwka8ZdtCA+fTalMOmbTRRsZJmT7HcehOmYYMAzYpMc1i8lNj6RzmQmE/ZQiSKBV3IDOEaCQu+Itnyo/Cv2Y3DwA9WVIQLvcjgHO7L393tAQemO35ZgaVcsiq2HjRzgV3VzPXgkWnGcKU3LjidycakMJeuCN3iwhcsoAesbhHGRohhoKNUoDdiInDfgKoYtsUb24sMcx55iw8g4gh8l5yN+T8R2oJI9D58hCo9zHFbty6J6GAh9a4EIlFg/cTVJ7dcYTI2QAeXVNeE+7So4xJllHIYr41JPgHuNBlo7Cn0hZFpmm5lugEEkHx9TU796zCuZLzD0tw4IslbjFU8iKwYtF5HfmjGEI80Xw4EAGTDrxAIT60INj0snUmz+X/2hZvtQqWVB41Ce5PqZVsVEJ9Au1a3rP+4YeQhQ0EOKZnD8uMhWtcr1sxRYRiBqqB6vTMmygkqkt80P7bJpmADZHtmscGuWquy1b2xO3u4JlP+dGZ07zQi1d3vAv+id5yIuo8=
